### NUMPY ASSIGNMENT
Big Data Analytics and Business Intelligence
(MCA203)
NumPy
1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

2. Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

3. Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise


In [2]:
import numpy as np

In [3]:
# 1.Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )
arr=np.array([1,2,3,4,5])
arr    

array([1, 2, 3, 4, 5])

In [9]:
reverse_array=arr[::-1]
reverse_array


array([5, 4, 3, 2, 1])

In [11]:
# 2. Compare the following numpy arrays: 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1,arr2)

True

In [35]:
# 3. Find the most frequent value and their indice(s) in the following arrays:

# i. x = np.array([1,2,3,4,5,1,2,1,1,1])
x = np.array([1,2,3,4,5,1,2,1,1,1])
# Find the most frequent value and its count in x
unique_values_x, counts_x = np.unique(x, return_counts=True)
most_frequent_value_x = unique_values_x[np.argmax(counts_x)]
indices_x = np.where(x == most_frequent_value_x)[0]

print("For array x:")
print("Most frequent value:", most_frequent_value_x)
print("Indices:", indices_x)


# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,])
unique_values_y, counts_y = np.unique(y, return_counts=True)
most_frequent_value_y = unique_values_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_value_y)[0]

print("\nFor array y:")
print("Most frequent value:", most_frequent_value_y)
print("Indices:", indices_y)


For array x:
Most frequent value: 1
Indices: [0 5 7 8 9]

For array y:
Most frequent value: 1
Indices: [0 1 2]


In [18]:
# 4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
# find 
# i. Sum of all elements
# ii. Sum of all elements row-wise
# iii. Sum of all elements column-wise
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())
print(gfg.sum(axis=1)) #row wise sum
print(gfg.sum(axis=0)) #column wise sum

45
[[14]
 [16]
 [15]]
[[20  9 16]]
